POST https://localhost:5165/Events HTTP/1.1
POST https://localhost:5165/Events HTTP/1.1
Content-Type: application/json

{
  "title": "Team Meeting",
  "description": "Monthly team alignment meeting.",
  "date": "2025-01-08",
  "startTime": "09:00:00",
  "endTime": "11:00:00",
  "location": "Conference Room 1",
  "maxAttendees": 20,
  "category": "Work",
  "adminApproval": true,
  "attendances": []
}
##########
POST https://localhost:5165/Events HTTP/1.1
Content-Type: application/json

{
  "title": "Team Meeting",
  "description": "Monthly team alignment meeting.",
  "date": "2025-01-08",
  "startTime": "09:00:00",
  "endTime": "11:00:00",
  "location": "Conference Room 1",
  "maxAttendees": 20,
  "category": "Work",
  "adminApproval": false,
  "attendances": []
}


##########
Post https://localhost:5165/Attendance HTTP/1.1
Content-Type: application/json

{
  "id": 0,
  "userId": "ab5050ef-461f-4da4-92e8-db48fbb7e1b7",
  "title": "zebbi",
  "description": "zebbi",
  "date": "2025-01-29T00:00:00.001Z",
  "startTime": "09:00:00",
  "endTime": "10:00:00"
}

###########
GET https://localhost:5165/Attendance/1 HTTP/1.1
Content-Type: application/json

###########

GET https://localhost:5165/Attendance HTTP/1.1
Content-Type: application/json
