POST https://localhost:5165/Events HTTP/1.1
Content-Type: application/json

{
  "id": 0,
  "title": "string",
  "description": "string",
  "date": "2025-02-01",
  "startTime": "22:16:18",
  "endTime": "22:16:18",
  "location": "string",
  "maxAttendees": 2147483647,
  "category": "string",
  "adminApproval": true,
  "attendances": []
}
