### Attend Event
POST https://localhost:5165/EventAttendance/Attend HTTP/1.1
Content-Type: application/json

{
  "UserId": "a12c6d9a-ff44-4e7a-a3b7-398d3772f3d3",
  "EventId": 2
}

### GET Event Attendees for Event ID 1
GET https://localhost:5165/EventAttendance/2/Attendees
Content-Type: application/json

### GET Events Attended by a Specific User
GET https://localhost:5165/EventAttendance/a12c6d9a-ff44-4e7a-a3b7-398d3772f3d3/attendances
Content-Type: application/json

####Submit Review for Event
POST https://localhost:5165/EventAttendance/SubmitReview 
Content-Type: application/json

{
"userId": "a12c6d9a-ff44-4e7a-a3b7-398d3772f3d3", "eventId": 2, "rating": 5, "feedback": "This event was gay!"
}