POST https://localhost:5165/Events HTTP/1.1
Content-Type: application/json

{
  "id": 0,
  "title": "string",
  "description": "string",
  "date": "2025-02-01",
  "startTime": "22:16:18",
  "endTime": "22:16:18",
  "location": "string",
  "maxAttendees": 2147483647,
  "category": "string",
  "adminApproval": true,
  "attendances": []
}


### DELETE Event with ID 1
DELETE https://localhost:5165/Events?id=1
Content-Type: application/json

###
GET https://localhost:5165/Events/Reviews/2 HTTP/1.1
Content-Type: application/json


###
GET https://localhost:5165/Events/rating/2 HTTP/1.1
Content-Type: application/json
