### Attend Event
POST https://localhost:5165/EventAttendance/Attend HTTP/1.1
Content-Type: application/json

{
  "UserId": "84e9da70-5220-49c3-b334-32144d0f82bf",
  "EventId": 2
}

### GET Event Attendees for Event ID 1
GET https://localhost:5165/Events/2/Attendees
Content-Type: application/json
